### ISSUE TITLE
Add means to pull  DB_DATABASE, DB_USERNAME, DB_PASSWORD from .env

### ISSUE THREAD

**Issue by iammikek** [sinnbeck/laravel-served#1]
I would like to make a change to allow the settings for DB etc to be pulled from .env rather than having to modify in config/served.php

can you add me as a user to this project so I can submit a pull request?

**Comment by sinnbeck** [comment]
@iammikek sounds like a fine idea. I would assume you can just fork and create a pr?

**Comment by iammikek** [comment]
Hi René

Great.

BTW you may recall via laracasts we changed the port in the config/served.php to use 3307. Oddly if I changed that in Laravel .env also to 3307 it throws an error:

SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `sessions` where `id` = SZc444Pjbr519zPXOEcI2MOXPGuK025yMYb8EMwT limit 1)

As I’m relatively new to docker, I’ll exclude picking up that setting for now. 

I’ll make a fork and then submit a PR this morning. 

Cheers
Mike

**Comment by sinnbeck** [comment]
@iammikek yeah it can be confusing. It works a bit like homestead. You use 3306 from inside laravel and 3307 from the database manager on your computer. Laravel is inside docker while your manager is outside
https://laravel.com/docs/7.x/homestead#connecting-to-databases

https://github.com/sinnbeck/laravel-served#mysql

**Comment by sinnbeck** [comment]
Can this be closed?
