### ISSUE TITLE
Can't connect to mysql outside docker

### ISSUE THREAD

**Issue by iammikek** [sinnbeck/laravel-served#11]
probably just me, but whats your normal process for interacting with the mysql DB?

I've tried to connect via the settings:
```
'mysql' => [
            'service' => 'mysql',
            'version' => '5.7',
            'port' => 3306,
            'root_password' => 'password',
            'database' => 'laravel',
            'username' => 'laravel',
            'password' => 'password',
        ],
```
 both with localhost + 127.0.0.1 via the Database Tab in phpstorm. No dice. Any advice?

**Comment by sinnbeck** [comment]
Check if the container is running with `php artisan served:list`

It might be a port inflict. If so, try setting another port (eg 3307), and run `php artisan served:up` again. After this try connecting on this port in phpstorm (still 3306 in laravel)

**Comment by sinnbeck** [comment]
![image](https://user-images.githubusercontent.com/13980140/94652795-e14e0b80-02fa-11eb-8abd-940001e2e3b4.png)
![image](https://user-images.githubusercontent.com/13980140/94653012-2e31e200-02fb-11eb-93b0-96de2e965396.png)

**Comment by sinnbeck** [comment]
Any luck getting this to work? Sadly I don't own a Mac to test on

**Comment by iammikek** [comment]
yeah. I got it to work when I changed the port with config/served.php
