### ISSUE TITLE
Allow means to run docker side by side, so you can work on multiple projects at one

### ISSUE THREAD

**Issue by iammikek** [sinnbeck/laravel-served#12]
When you install Laravel served we are presented with the prompt to run the development server.

```
Visit the development server at: http://localhost:8095
```

How feasible would it be to allow the port to be changed, so that multiple instances can be run side by side?

would be good to have access to the port within config/served.php

**Comment by sinnbeck** [comment]
Actually you can. Just set or change it here

https://github.com/sinnbeck/laravel-served/blob/master/src/config/served.php#L44

Then run `php artisan served:up`

**Comment by sinnbeck** [comment]
Can this be closed?

**Comment by iammikek** [comment]
Yes indeed.
