### ISSUE TITLE
running 'artisan served:up' displays extra url for dev server that doesn't resolve.

### ISSUE THREAD

**Issue by iammikek** [sinnbeck/laravel-served#19]
I get the following:

```
Laravel has been
 __   ___  __        ___  __  
/__` |__  |__) \  / |__  |  \ 
.__/ |___ |  \  \/  |___ |__/ 
                              
Visit the development server at:
http://localhost:8095
https://localhost:4443
```

this last url doesn't resolve.

**Comment by sinnbeck** [comment]
Interesting. Can you post an image of what it shows?

**Comment by iammikek** [comment]
see above. extra url is https://localhost:4443

**Comment by sinnbeck** [comment]
I mean a screenshot of the error in your browser :)

Honestly I have only tested it properly in Chrome. I imported the certificate using the guide here https://github.com/sinnbeck/laravel-served#web

**Comment by iammikek** [comment]
aha. 

the error relates to missing cert:

```
This site can’t be reachedlocalhost unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_CLOSED
```
I best read the readme next time 🤦

**Comment by sinnbeck** [comment]
It could also be due to a bad image build. You can try recreating everything

```
php artisan served:teardown //will remove everything 
php artisan served:up //will create everything again

**Comment by iammikek** [comment]
I'm checking install instructions and I don't have a localhost.crt in /storage/app/served/web/

**Comment by sinnbeck** [comment]
Weird! Do you see it in your forked repo? /Images/stubs

**Comment by sinnbeck** [comment]
https://github.com/sinnbeck/laravel-served/blob/master/src/Images/stubs/localhost.crt

**Comment by iammikek** [comment]
I can see it images/stubs. 
Your install instructions suggests that it would be found in /storage/app/served/web/ directory. 

```
If you are trying to use the https address, you will be shown a certificate error. To fix this in Chrome, open chrome://settings/certificates and select the Authorities tab. Click import and find the localhost.crt in your /storage/app/served/web/ directory
```
BTW process for this is different on Mac chrome. I'll update the README with details once I've got this installed.

**Comment by sinnbeck** [comment]
It should copy it into that folder when running `php artisan served:up`

**Comment by sinnbeck** [comment]
Found the error. It only copies it over when using apache. Will release fix later today

https://github.com/sinnbeck/laravel-served/blob/master/src/Images/ApacheImage.php#L32
Vs
https://github.com/sinnbeck/laravel-served/blob/master/src/Images/NginxImage.php#L27

**Comment by sinnbeck** [comment]
You can manually copy both files over and run `php artisan served:up` again

Or switch to apache for now (and run `served:up`)

**Comment by iammikek** [comment]
theres an error for it in the install process too:

> ERROR : COPY failed: stat /var/lib/docker/tmp/docker-builder136502001/storage/app/served/web/localhost.key: no such file or directory

**Comment by sinnbeck** [comment]
v0.6.2 has been released with a fix :)

**Comment by iammikek** [comment]
@sinnbeck nice. works now for Nginx.

**Comment by sinnbeck** [comment]
@iammikek with certificate and no errors?

I am thinking of making a real documentation page with sections for each part :) the current way might get bloated

**Comment by iammikek** [comment]
@sinnbeck yeah. works with certs. the installation method is different on Mac compared to windows. I'll try and uninstall it and then cover that in the installation notes (will do this on a separate PR)

**Comment by sinnbeck** [comment]
Awesome. I will try getting to work with Firefox and add that as well
