### ISSUE TITLE
Flag for showing commands being run

### ISSUE THREAD

**Issue by sinnbeck** [sinnbeck/laravel-served#20]
Add a flag to commands that allows showing what commands are run. Will need some regex replacements to ensure proper values are show (not "variables")

**Comment by vijaykrishna536** [comment]
Hi @sinnbeck Please explain a bit more about the issue

**Comment by sinnbeck** [comment]
Sure
https://github.com/sinnbeck/laravel-served/blob/master/src/Containers/PhpContainer.php#L10
https://github.com/sinnbeck/laravel-served/blob/master/src/Containers/PhpContainer.php#L28
For example when starting a container, we run a docker command like this. The Process component from symfony then replaces these "variables" when running the command.

It would be nice for the user (and testing) if the actual command being run could be shown

**Comment by pfaffenrodt** [comment]
Interesting, this year it is required that a `hacktoberfest` is added in topic of the repository
My PR is marked as:
> Ineligible Repository
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the  "hacktoberfest" topic to their repository if they wish to participate.

**Comment by sinnbeck** [comment]
Added topic to project. Thanks for the help!
