### ISSUE TITLE
Enable/disable xdebug or multiple php instances 

### ISSUE THREAD

**Issue by sinnbeck** [sinnbeck/laravel-served#27]
Currently you need to rebuild the php image to turn xdebug on and off. This thread is for working on a better way. Perhaps running multiple versions of php, or having an easy way to turn it on/off on the fly.

https://github.com/sinnbeck/laravel-served/issues/25#issuecomment-720344288

**Comment by sinnbeck** [comment]
As a possible solution, it is now possible to enable/disable xdebug using `php artisan served:xdebug enable` and `php artisan served:xdebug disable`.

If anyone wants to try it out, it can be installed using
```
composer require sinnbeck/laravel-served:dev-xdebug 
```
@zendrax

**Comment by zendraxl** [comment]
@sinnbeck in my mind that is far better than having to rebuild the container. Thanks for listening.

**Comment by sinnbeck** [comment]
@zendraxl Glad to hear that you like it. It is now part of the main branch :)
