### ISSUE TITLE
Setting up Laravel-served with phpstorm

### ISSUE THREAD

**Issue by iammikek** [sinnbeck/laravel-served#30]
Hiya sinnbeck,
Do you have any advice on how to set up phpstorm with Laravel-served?

I'm trying to set a remote PHP interpreter. When I select
Preferences > PHP > CLI Interpreter > Add New (Docker) I cant see the image from the list.

Have you had any success with this and be able to share how to do it?

**Comment by sinnbeck** [comment]
Hi Mike

This is how I set it up locally :) I just quickly created a new project called laravel8 and spun it up. After that I can select it here.
![image](https://user-images.githubusercontent.com/13980140/107917362-1b494280-6f68-11eb-82eb-ef7eede305ee.png)

**Comment by iammikek** [comment]
@sinnbeck Thanks René. I'll give that a go :P

**Comment by iammikek** [comment]
Thanks. I've now got PHPStorm recognising the docker instance. 
Any tips on how to get XDebug playing?
![Screenshot 2021-03-05 at 21 32 35](https://user-images.githubusercontent.com/94362/110175890-5bc70e00-7dfa-11eb-8646-71d3a3ebbc97.png)
Specifically:
![Screenshot 2021-03-05 at 21 34 22](https://user-images.githubusercontent.com/94362/110176037-9a5cc880-7dfa-11eb-85b1-1f422ae1a626.png)

**Comment by sinnbeck** [comment]
Start by changing the port on the left (9000,90003) to 9001. Next create a remote debug config. It requires an IDE key. Use phpinfo() to find it

**Comment by iammikek** [comment]
Great. switched to port 9001. I can see via phpinfo that ide_key = served. I've added this key to DBGp Proxy settings in phpstorm.

![Screenshot 2021-03-06 at 10 57 57](https://user-images.githubusercontent.com/94362/110204432-db8cc100-7e6a-11eb-8878-d74667489084.png)

Previously I've added autostart config to xdebug (when I've done this via vagrant). In this case, would you expect 
`http://localhost:8095/?XDEBUG_SESSION_START=served` to trigger it (if I've got listen enabled in PHPSTORM).

Can't be far off now :P

**Comment by sinnbeck** [comment]
Hope you got it working. I use this setup
![image](https://user-images.githubusercontent.com/13980140/110327133-e043a780-8019-11eb-81d0-92dbec76e82a.png)
