### ISSUE TITLE
'Tests\TestCase' not found in laravel-served/tests/Unit/DockerImageTest.php:13

### ISSUE THREAD

**Issue by iammikek** [sinnbeck/laravel-served#5]
If I run 'composer test' in root directory, I get the following error:

Class 'Tests\TestCase' not found in ~/laravel8/laravel-served/tests/Unit/DockerImageTest.php:13

This appears because the tests are being run outside of a Laravel install. 

Switching to running tests within Laravel8 install

with the following
```
        "sinnbeck/laravel-served": "@dev"
```
and

```
 "repositories": [
        {
            "type": "path",
            "url": "~/laravel8/laravel-served",
            "options": {
                "symlink": true
            }
        }
    ]
```
in composer.json

./vendor/bin/phpunit ../laravel-served/tests/Unit

I get the following:

1) Tests\Unit\DockerImageTest::it_can_make_apache_docker_file
Error: Call to undefined method Tests\Unit\DockerImageTest::getExpectedContent()

and similar for other tests.

@sinnbeck can you let me know how you've got your package set up locally and what command you run to run your DockerImageTest class?

**Comment by iammikek** [comment]
I didn't spot that you have Laravel installed as a dev dependency. Run composer install. Job done

**Comment by sinnbeck** [comment]
Yeah I also set up some auto loading and installed the orchestra test package
