### ISSUE TITLE
Let served make a proper name if none is set (instead of defaulting to 'served')

### ISSUE THREAD

**Issue by iammikek** [sinnbeck/laravel-served#7]
@sinnbeck I'm looking at ways we could introduce this feature and wonder how you'd like to approach it?

Are you imagining something like how heroku does eg "airy-craig" or "soaring-peaks"?

We would need to preserve the name once it was created. Would it be viable for us to write this name into the .env as SERVER_NAME?
 
I came across https://mattstauffer.com/blog/generating-synonymous-heroku-style-server-names-with-lumen/ which might give us a head start.

What do you think?

**Comment by sinnbeck** [comment]
Really interesting. We just need to make sure that it does not change between builds. I worry people will complain if we add it to their env without asking. I was considering running slug on the folder name

**Comment by sinnbeck** [comment]
If you wanna discuss on.. Discuss :p I am on Sinnbeck#9951

**Comment by iammikek** [comment]
Using a folder name sounds sensible. 

So we'd default to that, as a slug, and then allow it to be overridden in the .env if required. 

We'd need to get access to it via a method that replaces the calls to 
```
$servedName = config('served.name');
```
so I guess we could introduce a method in a new trait for this?

**Comment by sinnbeck** [comment]
Yeah sounds like a good plan. Use config if not null and fallback to slugged folder name

**Comment by sinnbeck** [comment]
@iammikek I am considering using  `Str::slug($name, '_')` to ensure that the name is always valid. Any thoughts?

**Comment by iammikek** [comment]
That sounds reasonable. we’d be looking at grabbing the directory name one level up from the vendor.

Having a think about best way to approach this via a test: are we able to compare the slugname with anything, or should we just check it’s not the value stored in config, and if it isn’t, it’s a slug.

**Comment by sinnbeck** [comment]
I have done a quick test with and this seems to do the job 

```
public function getProjectFolderName(): string
    {
        return Str::afterLast(base_path(), '/');
    }
```
and something like this go get the proper name
```
public function projectName(): string
    {
        if ($configName = config('served.name')) {
            if (!$this->testAllowedCharacters($configName)) {
                throw new \Exception(); //replace with proper exception
            }

            return $configName;
        }

        return Str::slug($this->getProjectFolderName(), '_');
    }

**Comment by iammikek** [comment]
Great stuff.

I’m happy if you want to take on the feature and to review any code if you want sanity checking.

**Comment by sinnbeck** [comment]
Sure. I will try to get something up and running soon :)

**Comment by iammikek** [comment]
Grand. My usual working day is client work between 9&5 although most of that is spent on Laracasts currently as I’m contracting for a financial services  company and dev is a bit light at the moment. My evenings are for when I get a bit of local dev time.
